services:
  - type: web
    name: smart-staff-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: 'false'
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: '*.render.com,smart-staff-api.onrender.com,localhost'
      - key: CORS_ALLOWED_ORIGINS
        value: 'https://smart-staff-8b633.web.app,http://localhost:5173,http://localhost:3000'
      - key: DATABASE_URL
        sync: false
    disks:
      - name: media
        mountPath: /opt/render/project/src/backend/media
        sizeGB: 1
