# Generated by Django 4.2.9 on 2026-04-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursal_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('recovered', 'Recovered')], default='pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('repayment_months', models.IntegerField(default=3)),
                ('amount_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='staff_management.staff')),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvanceRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payroll_month', models.DateField()),
                ('amount_recovered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('salary_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='salary_advances.salaryadvance')),
            ],
            options={
                'verbose_name': 'Salary Advance Recovery',
                'verbose_name_plural': 'Salary Advance Recoveries',
                'ordering': ['payroll_month'],
                'unique_together': {('salary_advance', 'payroll_month')},
            },
        ),
        migrations.AddIndex(
            model_name='salaryadvance',
            index=models.Index(fields=['staff', 'status'], name='salary_adva_staff_i_1eb073_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryadvance',
            index=models.Index(fields=['requested_date'], name='salary_adva_request_9fe001_idx'),
        ),
    ]
