# Generated by Django 4.2.9 on 2026-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_type', models.CharField(choices=[('total_staff', 'Total Staff'), ('total_payroll', 'Total Payroll'), ('pending_advances', 'Pending Salary Advances'), ('department_count', 'Department Count'), ('active_staff', 'Active Staff'), ('teaching_vs_nonteaching', 'Teaching vs Non-Teaching'), ('average_salary', 'Average Salary'), ('gender_distribution', 'Gender Distribution')], max_length=50)),
                ('value', models.JSONField()),
                ('calculated_date', models.DateTimeField(auto_now_add=True)),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('period_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dashboard Metric',
                'verbose_name_plural': 'Dashboard Metrics',
                'ordering': ['-calculated_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('staff_summary', 'Staff Summary Report'), ('payroll_summary', 'Payroll Summary Report'), ('salary_advance_summary', 'Salary Advance Summary'), ('department_analysis', 'Department Analysis'), ('category_analysis', 'Category Analysis'), ('attendance_analysis', 'Attendance Analysis'), ('tax_report', 'Tax Report'), ('bank_advise', 'Bank Advise')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('format_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('filters', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('download', 'Downloaded')], max_length=20)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='reports_aud_model_n_dc47ea_idx'), models.Index(fields=['timestamp'], name='reports_aud_timesta_09f1cf_idx')],
            },
        ),
    ]
