# Generated by Django 4.2.9 on 2026-04-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_worked', models.IntegerField(default=30)),
                ('working_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('approved', 'Approved'), ('disbursed', 'Disbursed')], default='draft', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursed_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-period', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.IntegerField(choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6'), (7, 'Month 7'), (8, 'Month 8'), (9, 'Month 9'), (10, 'Month 10'), (11, 'Month 11'), (12, 'Month 12')])),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_taxable', models.BooleanField(default=False)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Payroll Earning',
                'verbose_name_plural': 'Payroll Earnings',
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Payroll Deduction',
                'verbose_name_plural': 'Payroll Deductions',
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='staff_management.staff'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['period', 'status'], name='payroll_pay_period__6c8c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['staff', 'period'], name='payroll_pay_staff_i_de4528_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('period', 'staff')},
        ),
    ]
