# Generated by Django 4.2.9 on 2026-04-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_kenya_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
