# Generated by Django 4.2.9 on 2026-04-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0004_alter_staff_kra_pin_alter_staff_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='StaffDeductionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apply_paye', models.BooleanField(default=True)),
                ('apply_nssf', models.BooleanField(default=True)),
                ('apply_sha', models.BooleanField(default=True)),
                ('sha_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apply_housing_levy', models.BooleanField(default=True)),
                ('full_salary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_configs', to='staff_management.staff')),
            ],
            options={
                'verbose_name': 'Staff Deduction Config',
                'verbose_name_plural': 'Staff Deduction Configs',
                'unique_together': {('staff',)},
            },
        ),
    ]
