# Generated by Django 4.2.9 on 2026-04-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0005_deduction_amount_alter_deduction_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationDeductionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apply_paye', models.BooleanField(default=True)),
                ('apply_nssf', models.BooleanField(default=True)),
                ('apply_sha', models.BooleanField(default=True)),
                ('sha_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apply_housing_levy', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_config', to='staff_management.designation')),
            ],
            options={
                'verbose_name': 'Designation Deduction Config',
                'verbose_name_plural': 'Designation Deduction Configs',
            },
        ),
        migrations.CreateModel(
            name='CategoryDeductionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apply_paye', models.BooleanField(default=True)),
                ('apply_nssf', models.BooleanField(default=True)),
                ('apply_sha', models.BooleanField(default=True)),
                ('sha_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apply_housing_levy', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_config', to='staff_management.staffcategory')),
            ],
            options={
                'verbose_name': 'Category Deduction Config',
                'verbose_name_plural': 'Category Deduction Configs',
            },
        ),
    ]
