# Generated by Django 4.2.9 on 2026-04-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0006_designationdeductionconfig_categorydeductionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydeductionconfig',
            name='custom_deductions',
            field=models.ManyToManyField(blank=True, related_name='category_configs', to='staff_management.deduction'),
        ),
        migrations.AddField(
            model_name='designationdeductionconfig',
            name='custom_deductions',
            field=models.ManyToManyField(blank=True, related_name='designation_configs', to='staff_management.deduction'),
        ),
        migrations.AddField(
            model_name='staffdeductionconfig',
            name='custom_deductions',
            field=models.ManyToManyField(blank=True, related_name='staff_configs', to='staff_management.deduction'),
        ),
    ]
